In [35]:
import numpy as np



In [48]:
w = np.matrix([[0,3.4,2.8,-3.1],
                [3.4,0,4.7,-1.2],
                [2.8,4.7,0,-5.9],
                [-3.1,-1.2,-5.9,0]])
theta = np.matrix([6.3,-4.3,-2.5,-9.6])
def sgn(x):
    if x >= 0:
        return 1
    else:
        return -1
x = np.matrix([[1,1,1,1],[1,1,1,-1],[1,1,-1,-1],[1,-1,-1,-1],
           [1,1,-1,1],[1,-1,-1,1],[1,-1,1,1],[1,-1,1,-1]])
x = x.T

In [49]:
np.tile(theta,(1,8)).shape

(1, 32)

In [50]:
w

matrix([[ 0. ,  3.4,  2.8, -3.1],
        [ 3.4,  0. ,  4.7, -1.2],
        [ 2.8,  4.7,  0. , -5.9],
        [-3.1, -1.2, -5.9,  0. ]])

In [51]:
xPro = np.c_[x,-x]
print(xPro)

[[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1]]


In [52]:
ans = np.dot(w,xPro)-theta.T
print(ans)
sgn = np.vectorize(sgn)
y = sgn(np.array(ans))
print(xPro)
print(np.matrix(y))

[[ -3.2   3.   -2.6  -9.4  -8.8 -15.6 -10.   -3.8  -9.4 -15.6 -10.   -3.2
   -3.8   3.   -2.6  -8.8]
 [ 11.2  13.6   4.2   4.2   1.8   1.8  11.2  13.6  -2.6  -5.    4.4   4.4
    6.8   6.8  -2.6  -5. ]
 [  4.1  15.9  15.9   6.5   4.1  -5.3  -5.3   6.5   0.9 -10.9 -10.9  -1.5
    0.9  10.3  10.3  -1.5]
 [ -0.6  -0.6  11.2  13.6  11.2  13.6   1.8   1.8  19.8  19.8   8.    5.6
    8.    5.6  17.4  17.4]]
[[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1]]
[[-1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1  1  1  1  1 -1 -1  1  1 -1 -1 -1  1  1  1 -1]
 [-1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]]


In [53]:
print(xPro)
print(np.matrix(y))


[[ 1  1  1  1  1  1  1  1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1 -1 -1 -1 -1 -1 -1  1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1 -1 -1 -1  1  1  1 -1 -1  1  1  1 -1 -1 -1  1]]
[[-1  1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  1 -1 -1]
 [ 1  1  1  1  1  1  1  1 -1 -1  1  1  1  1 -1 -1]
 [ 1  1  1  1  1 -1 -1  1  1 -1 -1 -1  1  1  1 -1]
 [-1 -1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]]


In [54]:
xPro = np.array(xPro)
xPro[0][13]
theta = np.array(theta)
theta[0][1]

-4.3

In [55]:
E = []
res = 0
w = np.array(w)
xPro = np.array(xPro)
theta = np.array(theta)
for k in range(16):
    for i in range(4):
        for j in range(4):
            res = res + (-1/2*w[i][j]*xPro[i][k]*x Pro[j][k])
        res = res + theta[0][i]*xPro[i][k]
    E.append(res)
    res = 0
                     

In [56]:
E

[-10.8,
 -12.000000000000002,
 19.8,
 28.199999999999996,
 -2.6000000000000023,
 1.0000000000000018,
 11.599999999999996,
 15.2,
 9.400000000000002,
 -30.199999999999996,
 -8.399999999999999,
 -17.200000000000003,
 7.6,
 -6.000000000000002,
 14.6,
 -20.200000000000003]

In [63]:
xPro

array([[ 1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1,  1,  1,  1],
       [ 1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1],
       [ 1, -1, -1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1, -1,  1]])

In [64]:
for k in range(16):
    for i in range(4):
        x = sgn(np.dot(w[i],xPro.T[k].T)-theta[0][i])
        xPro[i][k] = x
xPro

array([[-1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1],
       [ 1,  1, -1, -1, -1, -1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1],
       [-1,  1,  1,  1, -1, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1, -1],
       [ 1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1,  1]])